apiVersion: v1               
kind: Service                
metadata:                    
  name: elasticsearch-clusterip
  labels:                    
    service: elasticsearch-clusterip
spec:                        
  type: ClusterIP
  selector:                   
    service: elasticsearch-statefullset #this map to the name of the deployment (with elasticsearch, it's supposed to be the statefullset)
  ports:                     
  - name: http               
    port: 9200               
    targetPort: 9200
    protocol: TCP            
  - name: transport          
    port: 9300               
    targetPort: 9300
    protocol: TCP   

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery # metadata:name of the service should match value of spec: serviceName of StatefulSet e.g. match with the line 8 of the file [04]elasticsearch.statefullset.yaml -> serviceName: elasticsearch-discovery
spec:
  clusterIP: None # headless service
  selector:
    service: elasticsearch-statefullset
  ports:
  - name: transport
    port: 9300