apiVersion: v1               
kind: Service                
metadata:                    
  name: elasticsearch-clusterip
  labels:                    
    service: elasticsearch-clusterip
spec:                        
  type: ClusterIP
  selector:                   
    service: elasticsearch-statefullset
  ports:                     
  - name: http               
    port: 9200               
    targetPort: 9200
    protocol: TCP            
  - name: transport          
    port: 9300               
    targetPort: 9300
    protocol: TCP   

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery # match with the line 8 of the file [04]elasticsearch.statefullset.yaml -> serviceName: elasticsearch-discovery
spec:
  clusterIP: None # headless service
  selector:
    service: elasticsearch-statefullset # for headless Services that define selectors, the endpoints controller creates Endpoints records in the API, and modifies the DNS configuration to return records (addresses) that point directly to the Pods backing the Service
  ports:
  - name: transport
    port: 9300