apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-configmap
  namespace: default
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0"
    elasticsearch.url: http://elasticsearch-clusterip:9200
    xpack.monitoring.ui.container.elasticsearch.enabled: true
    elasticsearch.username: kibana
    elasticsearch.password: P@ssword123