apiVersion: v1
kind: Service
metadata:
  name: kibana-loadbalancer
  labels:
    component: kibana-loadbalancer
spec:
  type: LoadBalancer
  selector:
    component: kibana-deployment
  ports:
  - name: http
    port: 80
    targetPort: http