apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: default
data:
    
  logstash.yml: |
    xpack.monitoring.elasticsearch.url: http://elasticsearch-statefullset:9200
    dead_letter_queue.enable: true
    xpack.monitoring.enabled: true
    xpack.monitoring.elasticsearch.username: logstash_system 
    xpack.monitoring.elasticsearch.password: P@ssword123

  pipelines.yml: |
    - pipeline.id: azureeventhubs
      path.config: "/usr/share/logstash/azureeventhubs.cfg"
  
  azureeventhubs.cfg: |
    input {
      azure_event_hubs {
        event_hub_connections => ["Endpoint=sb://iaks-eventhub-namespace.servicebus.windows.net/;SharedAccessKeyName=mssagepolicy;SharedAccessKey=sQGbvpMmBB76n+uOxrw59Km3HRrY7W9urF4tK/VoMHg=;EntityPath=iaks-eventhub"]
        threads => 2
        decorate_events => true
        consumer_group => "$Default"
        storage_connection => "DefaultEndpointsProtocol=https;AccountName=iaksstorageaccount;AccountKey=MCUPo9tyBlYjBaY9512FhfBtGXZtOl7G+41sqXoLCLL4IHEyZa/8+Cs7GouhMAEr5JAn+qng7r67R4nk0hUZyA==;EndpointSuffix=core.windows.net"
        storage_container => "iakscontainer"
        }
    }
    filter {
    }
    output {
      elasticsearch {
        hosts => [ "elasticsearch-statefullset:9200" ]
        user => "elastic"
        password => "P@ssword123"
        index => "azureeventhub-%{+YYYY.MM.dd}"
      }
    }

  logstash.conf: |