apiVersion: v1
kind: Service
metadata:
  name: logstash-clusterip
  labels:
    component: logstash-clusterip
spec:
  type: ClusterIP
  selector:
    component: logstash-clusterip
  ports:
  - name: http
    port: 80
    targetPort: http