apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
  labels:
    component: logstash-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
     component: logstash-deployment
  template:
    metadata:
      labels:
        component: logstash-deployment
    spec:
      containers:
      - name: logstash-container
        image: docker.elastic.co/logstash/logstash:6.4.1
        volumeMounts:
        - name: logstash-configmap
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
        - name: logstash-configmap
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
        - name: logstash-configmap
          mountPath: /usr/share/logstash/azureeventhubs.cfg
          subPath: azureeventhubs.cfg
        - name: logstash-configmap
          mountPath: /usr/share/logstash/config/pipelines.yml
          subPath: pipelines.yml
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: http
      volumes:
        - name: logstash-configmap
          configMap:
            name: logstash-configmap